Company_Blog/models.py
from Company_Blog import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model,UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer,primary_key = True)
    profile_image = db.Column(db.String(20),nullable = False,default = 'default_profile.png')
    email = db.Column(db.String(64),unique = True,index = True)
    username = db.Column(db.String(64),unique = True,index = True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost',backref = 'author',lazy = True)

    def __init__(self,email,username,password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'Username :{self.username}'    


class BlogPost(db.Model):
    users = db.relationship(User)
    id = db.Column(db.Integer,primary_key = True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'),nullable = False)
    date = db.Column(db.DateTime,nullable = False,default = datetime.utcnow)
    title = db.Column(db.String(120),nullable = False)
    text = db.Column(db.Text,nullable = False)

    def __init__(self,title,text,user_id):
        self.title = title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post ID : {self.id} , Post Title : {self.title} , Post Date : {self.date}"

Company_Blog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user
from Company_Blog.models import User

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo(
        'pass_confirm', message='Passwords must match')])
    pass_confirm = PasswordField(
        'Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self, field):
        if User.quesr.filter_by(email=field.data).first():
            raise ValidationError(
                message='Your Email has already been registered')

    def check_username(self, field):
        if User.quesr.filter_by(username=field.data).first():
            raise ValidationError(
                message='Your Username has already been registered')


class UpdateUserForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', FileAllowed=(['jpg', 'png']))
    submit = SubmitField('Update')

    def check_email(self, field):
        if User.quesr.filter_by(email=field.data).first():
            raise ValidationError(
                message='Your Email has already been registered')

    def check_username(self, field):
        if User.quesr.filter_by(username=field.data).first():
            raise ValidationError(
                message='Your Username has already been registered')

Company_Blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
import os


app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'

from Company_Blog.core.views import core
from Company_Blog.error_pages.handlers import error_pages
from Company_Blog.users.views import users
app.register_blueprint(error_pages)
app.register_blueprint(core)
app.register_blueprint(users)

Company_Blog/core/views.py
from flask import render_template,request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

Company_Blog/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from Company_Blog import db
from Company_Blog.models import User,BlogPost
from Company_Blog.users.forms import LoginForm,RegistrationForm,UpdateUserForm
from Company_Blog.users.picture_handler import add_profile_picture

users = Blueprint('users',__name__)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))
@users.route('/register',methods = ['GET','POST'])
def register():
    form = RegistrationForm()
    if(form.validate_on_submit):
        user = User(email = form.email.data,username = form.username.data,password = form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks For Registration')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)

@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if(form.validate_on_submit):
        user = User.query.filter_by(email = form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Login Success!')

            next = request.args.get('next')
            
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.htmml',form=form)        

@users.route('/account',methods=['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()
    if(form.validate_on_submit):
        if form.picture.data:
            username = current_user.username
            pic = add_profile_picture(form.picture.data,username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data

        db.session.commit()
        flash('Account Updated') 
        redirect(url_for('users.account')) 
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)    


@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author = user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

Company_Blog/templates/account.html
{% extends 'base.html' %}
{% block content %}
<div class = 'jumbotron'>
<div align='center'>
    <h1>Welcome {{current_user.username}}</h1>
    <img align = 'center' src="{{url_for('static',filename = 'profile_pics/'+current_user.profile_image)}}" alt="">
</div>
</div>
<div class="container">
    <form method="POST">
        {{form.hidden_tag()}}
        <div class='form-group'>
            {{form.username.label(class='form-group')}}{{form.username(class='form-control')}}
        </div>
        <div class='form-group'>
            {{form.email.label(class='form-group')}}{{form.email(class='form-control')}}
            
        </div>
        <div class='form-group'>
            {{form.picture.label(class='form-group')}}{{form.picture(class='form-control')}}
            
        </div>
        <div class='form-group'>
            {{form.submit(class='btn btn-primary')}}
            
        </div>
        
    </form>
</div>
    
{% endblock  %}

Company_Blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    
   <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</head>

<body>
    <ul class="nav">
        <li class="nav-link">
            <a href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('core.info')}}">About</a>
        </li>
        {% if  current_user.is_authenticated %}
            
        
        <li class="nav-link">
            <a href="{{url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-link">
            <a href="#">Create Post</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.logout')}}">Log Out</a>
            {% else %}
        </li>   
        <li class="nav-link">
            <a href="{{url_for('users.register')}}">Register</a>
        </li>
        <li class="nav-link">
            <a href = "{{url_for('users.login')}}">Log In</a>
        </li>
    </ul>
    {% endif %}

    <div class='container'>
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

Company_Blog/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class = "jumbotron">
    <h1>Welcome to WebDynasty</h1>
</div>
{% endblock %}

Company_Blog/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class = "jumbotron">
        <h1>About Us</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In, corporis ipsam excepturi, nesciunt possimus et blanditiis ipsa cumque iste earum libero culpa necessitatibus omnis temporibus sed, porro recusandae quis dicta.</p>
    </div>
{% endblock%}

Company_Blog/templates/login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email}}<br>
    {{form.password.label}}{{form.password}}<br>
    {{form.submit()}
</form>
    
{% endblock  %}

Company_Blog/templates/register.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
{{form.hidden_tag()}}
{{form.email.label}}{{form.email}}<br>
{{form.username.label}}{{form.username}}<br>
{{form.password.label}}{{form.password}}<br>
{{form.pass_confirm.label}}{{form.pass_confirm}}<br>
{{form.submit()}
</form>
    
{% endblock  %}

Company_Blog/templates/user_blog_posts.html
{% extends 'base.html' %}
{% block content %}
    <div class = 'container'>
        <div class = 'jumbotron'>
            <div align = 'center'>
                <h1>Welcome {{user.username}}</h1>
                <img src="{{'static',filename = 'profile_pics/'+user.profile_image}}" alt="">
            </div>
        </div>
        {% for post in blog_post.items  %}
        <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id = post.id)}}">{{post.title}}</a></h2>
        Written By : <a href="{{url_for('users.user_post',username=post.author.username)}}">{{post.author.username}}</a>
        <p class = 'text-muted'>Published On : {{post.date.strftime("%Y-%m-%d")}}</p>
        <br>
        {{post.text}}
        <br>
    {% endfor %}
    </div>

    <nav aria-label="Page Navigation example">
        <ul class = "pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge = 1,right_edge=1,left_current=1,right_current=2)  %}
                {% if blog_posts.page == page_num %}
                    <li class='page-item disabled'>
                        <a class="page-link" href="url_for('users.user_posts',username = user.username,page=page_num)">{{page_num}}</a>
                    </li>
                {% else %}  
                <li class='page-item'>
                    <a class="page-link" href="url_for('users.user_posts',username = user.username,page=page_num)">{{page_num}}</a>
                </li>
                {% endif %}
            {% endfor %}
        </ul>

    </nav>
    
{% endblock  %}